In [1]:
# Question 1

import numpy

def arrays(arr):
    
    a=numpy.array(arr,float)
    
    n=len(a)
    k=n//2
    i=0
    while i<k:
        t=a[n-i-1]
        a[n-i-1]=a[i]
        a[i]=t
        i+=1
    
    return a
    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6
[6. 5. 4. 3. 2. 1.]


In [2]:
# Qustion 2

import numpy

num=list(map(int,input().split(' ')))

arr=numpy.array(num)

ar=numpy.reshape(arr,(3,3))

print(ar)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Question 3

import numpy

lst=list(map(int,input().split(' ')))
n=lst[0]
m=lst[1]

num=[]

for i in range(n):
    nu=list(map(int,input().split(' ')))
    num.append(nu)
    
arr2d=numpy.array(num)

print(arr2d.T)
print(arr2d.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
# Question  4

import numpy
P, N, M = map(int,input().split())
A = numpy.array([input().split() for _ in range(P)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.concatenate((A, B), axis = 0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [5]:
# Question 5

import numpy

N = tuple(map(int, input().split()))

                
print(numpy.zeros(N, dtype = numpy.int))
print(numpy.ones(N, dtype = numpy.int))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [6]:
# Question 6

import numpy
numpy.set_printoptions(legacy='1.13')

lst=list(map(int,input().split(' ')))
n=lst[0]
m=lst[1]

print(numpy.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
# Question 7

import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
B=numpy.array([list(map(int,input().split())) for i in range(n)])
print(A+B,A-B,A*B,A//B,A%B,A**B,sep='\n')


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [8]:
# Question 8

import numpy
numpy.set_printoptions(legacy='1.13')

arr=numpy.array(list(map(float,input().split(' '))))

print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [9]:
# Question 9

import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))


2 2
1 2
3 4
24


In [1]:
# Question  10

import numpy

N, M = map(int, input().split())
s = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(s, axis=1), axis=0))

4 2
2 5
3 7
1 3
4 0
3


In [2]:
# Question 11

import numpy

lst=list(map(int,input().split(' ')))
n=lst[0]
m=lst[1]

lst=[]
for i in range(n):
    lst.append(list(map(int,input().split(' '))))
    
arr=numpy.array(lst)

print(numpy.mean(arr,axis=1))
print(numpy.var(arr,axis=0))
print(round(numpy.std(arr),11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [3]:
# Question  12

import numpy


n=int(input())

lst=[]
for i in range(n):
    lst.append(list(map(int,input().split(' '))))
    
arrA=numpy.array(lst)

lst=[]
for i in range(n):
    lst.append(list(map(int,input().split(' '))))
    
arrB=numpy.array(lst)

print(numpy.matmul(arrA,arrB))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [4]:
# Question 13

import numpy

arr1=numpy.array((list(map(int,input().split(' ')))))
arr2=numpy.array((list(map(int,input().split(' ')))))

print(numpy.inner(arr1,arr2))
print(numpy.outer(arr1,arr2))

0 1
2 3
3
[[0 0]
 [2 3]]


In [5]:
# Question  14

import numpy

arr1=numpy.array((list(map(float,input().split(' ')))))

n=int(input())

print(numpy.polyval(arr1,n))


1.1 2 3
0
3.0


In [7]:
# Question  15

import numpy

n=int(input())
lst=[]
for i in range(n):
    lst.append(list(map(float,input().split(' '))))
    
arr=numpy.array(lst)

print(round(numpy.linalg.det(arr),2))

2
1.1 1.1
1.1 1.1
0.0
